version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "5001:5001"
    depends_on:
      - dynamodb
      - dynamodb_admin
  dynamodb:
    image: amazon/dynamodb-local
#    restart: unless-stopped
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath .
    volumes:
      - dynamodb-volume:/home/dynamodblocal
  dynamodb_admin:
    build:
      context: .
      dockerfile: docker/admin.Dockerfile
    ports:
    - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - AWS_REGION=ap-northeast-2
      - AWS_ACCESS_KEY_ID=example
      - AWS_SECRET_ACCESS_KEY=example
    depends_on:
      - dynamodb

volumes:
  dynamodb-volume: